### ISSUE TITLE
NBT crash with Tier 2 bag

### ISSUE THREAD

**Issue by devryb** [lorddusk/Bagginses#10]
http://pastebin.com/XsK5vGqt

**Comment by lorddusk** [comment]
Update

**Comment by devryb** [comment]
What version is this for? It still crashes and dupe in version 2.0.2

**Comment by lorddusk** [comment]
Well, give me more details. How do I replicate this, because a crashlog
alone does NOT help.

**Comment by devryb** [comment]
For the crash place items into the bag and use the number keys to switch items in your hot bar. If you escape out of the bag and it has changed location in your hot bar it will crash your client and the server.
For the dupe issue just replicate as above but use a secondary bag that you swap into the same hot bar location as the bag you currently have open again using the number keys. It will duplicate the bag contents into the secondary one.

**Comment by lorddusk** [comment]
This got fixed in 2.0.1 ..... Get me a fresh crashlog, because somehow I
think you are not updating...

**Comment by jaredlll08** [comment]
Just looking at the crash log... On line 52 
bagginses{@MODVERSION@} [Bagginses] (Bagginses-1.2.1.jar)

**Comment by lorddusk** [comment]
I know, but he said it was also doing it in 2.0.2. Which I don't believe and can't test right now.

**Comment by devryb** [comment]
Server Crash:
http://pastebin.com/Fu47Nqnu

Client Crash:
http://pastebin.com/xBQqpZhX

**Comment by lorddusk** [comment]
Fixed in 2.1.x
