### ISSUE TITLE
Bag contents overwritten

### ISSUE THREAD

**Issue by zlyfire** [lorddusk/Bagginses#12]
Using v1.2.1 in the Regrowth modpack. I had two bags on my hotbar, a white tier 2 and a yellow tier 2. I went out exploring and found a hive, so I went to open my white bag, and it wouldn't open, then my world showed signs of temporary lag. The bag then kicked open and showed the contents of yellow bag (which was three foodstacks and clay jars.) All of my tools (white bag) were now erased and replaced.

**Comment by lorddusk** [comment]
that's fixed in the later versions.

**Comment by lorddusk** [comment]
Fixed in 2.1.x
