### ISSUE TITLE
Easier Inventory/Bag Transfer

### ISSUE THREAD

**Issue by zlyfire** [lorddusk/Bagginses#13]
On the newest version (2.0.1) and there isn't shift-click support into the bag (out of bag works though) and I can't space-click everything into there (forget if that's vanilla, NEI, or inv tweaks ability). There is also no inv tweaks sorting in the bags.
Would it be possible to add those things? (Shift-click support, might be a bug in this version?; Space-click/Inv Tweaks support)

**Comment by lorddusk** [comment]
Added into 2.1 :D
