### ISSUE TITLE
Change the config file to use a blacklist rather than a whitelist.

### ISSUE THREAD

**Issue by Rostepher** [lorddusk/Bagginses#18]
The config file uses a whitelist to dictate which bags can hold what types of items, with support for specifying mod names. This is cumbersome for the most general use case, which is to whitelist every item. It would be better, at least in my opinion, to change the config file to use a black list. Then modders could blacklist items that cannot appear in bags or if left blank (as is the default), bags will be able to hold any item.

Another possible solution to this problem would be to add a single global boolean config option to whitelist all items for all bags.

**Comment by Slyrooster** [comment]
Hi I'm having a hard time finding out how to whitelist mods for bagginses. Is it possible you can provide an example on how to do so? Thanks!

**Comment by Rostepher** [comment]
@Slyrooster This isn't really the place for asking how to whitelist mods. This is an issue to change the config file to use a blacklist, as opposed to a whitelist.

In the config file, for each bag listed you will need to specify mods or items that are whitelisted for that particular bag. It should have an example in the comment at the top of the file. Something like `mod_name:item_name`. You can separate mods and items with commas. For example to whitelist cobblestone and dirt: `minecraft:cobblestone, minecraft:dirt`. To whitelist all of the base minecraft items `minecraft:*`. To whitelist all items in your pack `*:*` works for me.

**Comment by Fortist** [comment]
I am also going to second this because this just straight up bad design.
Or rather, more work than it's worth to add tons of items and blocks to the config for each backpack.

You should at least have a keyword or something (like "ALL") to allow any and every block and item to be put in certain bags.

Oh this is months old, I guessing you dont actually want the majority to use your mod.

**Comment by lorddusk** [comment]
If you would've actually read the config. you could've seen that *:* adds
EVERY item to the whitelist.
Also I'm working on this. And the majority not using my mod? You mean the
mod that is in AgSkies 2 and currently on FC1 and FTB Unstable? Kappa

**Comment by ThomasRules2000** [comment]
Would it be possible to change the default setting for whitelisting items to false/blacklist? It just seems a bit odd that I would have to edit a config just to allow items to be in my world

**Comment by AKTheKnight** [comment]
Done
