### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by UniversalLP** [lorddusk/Bagginses#24]
Hey, it seems that it's still possible to duplicate items using the number hotkeys:

![Gif](http://i.imgur.com/phe14ib.gif)

Here's what I did:
- Have two stacks in the bag
- Use the number keys to move one stack to the slot where the bag is, moving the bag into another slot 
- Grab the bag and shift-click on the other stack so it lands in the inventory
- Throw the bag out of the gui

When you now pick up the bag it still contains a stack.

Version used: 2.1.5b

**Comment by AKTheKnight** [comment]
Thanks for pointing this out. We're still having trouble finding a solution in order to prevent this happening. Hopefully I will have one soon :)
