### ISSUE TITLE
[Feature Request] Achievements

### ISSUE THREAD

**Issue by SnowShock35** [lorddusk/Bagginses#28]
Hi,

I'd like to make a feature request for Bagginses. Here it is... 

**What is the suggestion?**
To have various achievements for the mod e.g. Bag crafting, upgrading etc.

**How would you go about doing this?**
Use standard Minecraft achievements and add them in with some code -- I'll leave you to figure that out :stuck_out_tongue: 

**Why?**
Because why not! Also, adds a sense of well-polished mod

Hope you like the suggestion and consider adding it your awesome mod

**Comment by lorddusk** [comment]
I won't be adding anything :O

**Comment by SnowShock35** [comment]
Ik that, you're not working on it anymore are you tho? Alex is, right?

**Comment by lorddusk** [comment]
AK took the honors of taking it of my hands for the unforeseen future. I might be back someday, who knows.

**Comment by SnowShock35** [comment]
Yeah, I heard about the whole full-time work no time to code on Twitter. Glad you're still sticking around in the community. I mean if it wasn't for you I'd be a nobody :heart:

**Comment by AKTheKnight** [comment]
Sneak peak of progress: http://prntscr.com/avlxmd

**Comment by AKTheKnight** [comment]
Added in 2.3.1 -1.9 and 2.4.1 -1.9.4
