### ISSUE TITLE
crash when opened creative tab and mouse over bag icon

### ISSUE THREAD

**Issue by tiarnia** [lorddusk/Bagginses#29]
[B#347]  Description: Rendering screen
[B#347]  
[B#347]  java.lang.NullPointerException: Rendering screen
[B#347]  	at nl.lang2619.bagginses.items.bags.Bags.func_77624_a(Bags.java:91)
[B#347]  	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:588)
[B#347]  	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:130)
[B#347]  	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:679)
[B#347]  	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
[B#347]  	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
[B#347]  	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:590)
[B#347]  	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:312)
[B#347]  	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
[B#347]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1072)
[B#347]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
[B#347]  	at net.minecraft.client.main.Main.main(SourceFile:124)
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#347]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#347]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by lorddusk** [comment]
It would be great if you could follow this link : https://github.com/lorddusk/Bagginses/blob/master/CONTRIBUTING.MD

**Comment by AKTheKnight** [comment]
Yup I'm going to need more info than this is in order to fix it. Please follow  https://github.com/lorddusk/Bagginses/blob/master/CONTRIBUTING.MD and then I will be able to help

**Comment by AKTheKnight** [comment]
This should be fixed in 2.3.0a - 1.9 so I am closing the issue. However as I didn't have the full log I am unsure if this was the same bug as the one I fixed. So feel free to reopen it WITH THE CORRECT LOGS
