### ISSUE TITLE
can't config

### ISSUE THREAD

**Issue by ejcmoorhouse** [lorddusk/Bagginses#31]
You say to config if you don't see bags ect. I am using 1.9 and your latest 2.3.0b however when I go to the mod options I can't seem to config the button is there but there is nothing to config.

**Comment by AKTheKnight** [comment]
We have not added the config to the gui yet. For now you will need to go to your minecraft directory.
Then to mods/bagginses and open bagginses.cfg

**Comment by lorddusk** [comment]
the config in the config folder.
