### ISSUE TITLE
whitelist=false config option not working

### ISSUE THREAD

**Issue by MechWarrior99** [lorddusk/Bagginses#37]
Changed whitelist=true to whitelist=false but none of the bags show up. With the config still on set to false I added a item and the bags I added the item to in the configs showed up but only that item would be allowed in, instead of only item not being allowed in.

**Version**
Minecraft 1.9.4
Bagginses 2.4.2

**Comment by AKTheKnight** [comment]
Hi, I am unable to reproduce this in either my dev workspace or in a new multimc instance. What forge version are you using?
