### ISSUE TITLE
[1.9.4] Not referring to RecipeSorter

### ISSUE THREAD

**Issue by copyyy** [lorddusk/Bagginses#43]
`[17:52:24] [Client thread/INFO] [FML/Forge]:   Unknown recipe class! nl.lang2619.bagginses.items.SoulBoundBagRecipe Modder please refer to net.minecraftforge.oredict.RecipeSorter`

Could cause crashes. See https://github.com/williewillus/Botania/issues/322#issuecomment-223598421.
[[Cannot tell if major change or if really that unstable but depending on @GirafiStudios comments it should be changed]]

**Comment by AKTheKnight** [comment]
Ahh thanks for pointing this out. I'll take a look at it and get this fixed :)

**Comment by AKTheKnight** [comment]
This should be fixed in 2.4.2a

(And git doesn't close unless in master branch)
