### ISSUE TITLE
[1.9.4] [2.4.2a] Tier 2 bags are not craftable

### ISSUE THREAD

**Issue by Galaxy2Alex** [lorddusk/Bagginses#44]
As pointed out [here](https://github.com/lorddusk/Bagginses/commit/69234da94c4443485a69b12e82627145c1a8c4ed), the ability to upgrade your bags to Tier 2 has, most likely accidental, but certainly without a warning, been removed.

Screenshot on how it's supposed to be: http://alex.ticklemy.wang/5hBLFT.png

**Comment by AKTheKnight** [comment]
Aww damn. I certainly didn't mean to do that. I'll get an update out asap to fix that, for now 2.4.2 should work for you (potential crash but nobody has reported it)

**Comment by BootyToast** [comment]
It looks like if you load a world with Tier 2 bags, the items occupying that extra space get erased as well. :O

**Comment by AKTheKnight** [comment]
Yeah that looks to have been an issue with some refactoring I did. This should all be fixed in 2.4.2b
