### ISSUE TITLE
Easy dupe method 

### ISSUE THREAD

**Issue by TheDumAmerican** [lorddusk/Bagginses#45]
You can place an item in the bag, pick up the bag from inventory slot, while holding the bag shift click the items out and place bag back in inventory. This keeps the items in the bag and puts them back in the inventory. Works with both tiers of bags. Version (Bagginses-2.1.1 Minecraft 1.7.10)

https://www.dropbox.com/s/agts1k57g6gmwzi/2016-06-05_09-43-44.mp4?dl=0

**Comment by AKTheKnight** [comment]
Yeah this is just the 1.7 version of #24 

I have also stopped development of both 1.7 and 1.8 versions of Bagginses (Both were before I took on the mod) but I will see if I can maybe get a fix out for this :)
