### ISSUE TITLE
3.0.0 not compatible with 1.9.4

### ISSUE THREAD

**Issue by TrikSteve** [lorddusk/Bagginses#48]
3.0.0 coming up on load with not compatible with 1.9.4 and requiring 1.10

**Comment by AKTheKnight** [comment]
Ahh my mistake. Might not be compatible with it then. I'll push out a build in a sec for 1.9.4

**Comment by AKTheKnight** [comment]
Bagginses 2.5.0 - 1.9.4 is now live on curse :)
