### ISSUE TITLE
Colourblind mode

### ISSUE THREAD

**Issue by AKTheKnight** [lorddusk/Bagginses#49]
To be researched. Make sure mod is accessible to all

**Comment by Vaygrim** [comment]
Color "Descriptions" / Keywords in tooltips for color-centric items go a long way.
Example: "Black Wool Bag", or "Ender Chest - Color Coded: White / White/ Light Blue", etc.
If you ever need someone to be a 'test subject' for some screenshots, lemme know.

**Comment by AKTheKnight** [comment]
That's along the lines of what I was thinking. I'll see what I can come up with and let you know. Thanks :)

**Comment by AKTheKnight** [comment]
Currently the bags show this when you mouse over them, and the name is the same as the colour. Is there anything else I can add to make it easier? http://imgur.com/a/E3vPS

Would have "Black Bag T2" as the name help?

**Comment by Vaygrim** [comment]
Honestly I like the "Black Bag, Tier 1" and "Black Bag, Tier 2" in the tooltip. Real quick reminder of what grade bag I have, and that's not even from a colorblind user standpoint.

**Comment by AKTheKnight** [comment]
Okay, I'll definitely look at adding that
