### ISSUE TITLE
Breaking blocks crashes.

### ISSUE THREAD

**Issue by drago15243** [lorddusk/Bagginses#54]
Saw pretty much the same issue, but I made a new post just to make sure. Any time I break a block, this happens:
http://pastebin.com/75kaaE2u

**Comment by lorddusk** [comment]
Fixed in https://github.com/lorddusk/Bagginses/commit/683c47d212aa4f6ea67c2a07a7bd2d0b1b717b03

**Comment by AKTheKnight** [comment]
Builds available here (curse not approved updates yet) http://jenkins.aktheknight.co.uk/view/Bagginses/
