### ISSUE TITLE
[1.10] Crash when breaking block

### ISSUE THREAD

**Issue by Kris1432** [lorddusk/Bagginses#55]
Forge: 1995
Pastebin: http://pastebin.com/UgZ81iRb
Mod Version: Bagginses-1.10-3.0.0.jar

Cause: Spawned in some iron ore and a pickaxe, went to break it and crashed with this.

**Comment by lorddusk** [comment]
Fixed in 3.0.0a

**Comment by Kris1432** [comment]
this also happens in 1.9.4 by the way Dusk.

**Comment by lorddusk** [comment]
Well yeah, grab 2.5.0a for 1.9.4 it's also fixed there.

**Comment by AKTheKnight** [comment]
Builds available here (curse not approved updates yet) http://jenkins.aktheknight.co.uk/view/Bagginses/

**Comment by Kris1432** [comment]
ah thanks!
