### ISSUE TITLE
MC1.10.0 version no block drops

### ISSUE THREAD

**Issue by eractnod** [lorddusk/Bagginses#56]
Added Bagginses-1.10-3.0.0 to my world, now, no blocks will drop when mining.  
Set B:"Should bags be able to pick up items when dropped"=false, no change.  
Set B:whitelist=false with no change.  
Added a bag name in the json file with no change.  
Put a bag in my inventory and chopped down a tree.  No blocks in inventory or the bag.

No blocks drop when mining them.  First noticed with a tree, got no wood blocks, then tried to mine dirt, nothing dropped.  Also breaks the mod Veinminer.  Tried Bagginses with and without veinminer with the same results.

**Comment by lorddusk** [comment]
Check with 3.0.0a please. I can't replicate this bug on that version.

**Comment by AKTheKnight** [comment]
Builds available here (curse not approved updates yet) http://jenkins.aktheknight.co.uk/view/Bagginses/

**Comment by eractnod** [comment]
Thank you sir, the 3.0.0a worked as expected.

**Comment by AKTheKnight** [comment]
Awesome. It was my mistake that caused the crash in the first place. Thanks for reporting it :)
