### ISSUE TITLE
Bug: NullPointerException during ItemDropEvent

### ISSUE THREAD

**Issue by sihrc** [lorddusk/Bagginses#58]
Bagginses Version: 1.10-3.0.0
Forge Version: 12.18.0.1984

Traceback:
https://gist.github.com/sihrc/0efebef7a91d17d19add48d008c73c96

Reproduction:
Don't have a lot of data points, but it seems to happen while mining underwater (sand? gravel? clay?).

**Comment by sihrc** [comment]
Not sure if this is the same as #54

**Comment by sihrc** [comment]
Ah the release candidate mentioned in that issue fixes the problem. Sorry for the issue spam.

**Comment by AKTheKnight** [comment]
It's fine, sorry I didn't manage to reply. I'd prefer people to create an issue, and it later turn out to be invalid. Than they never create an issue and it never gets fixed. Thank you :)
