### ISSUE TITLE
[1.2] Duplication bug

### ISSUE THREAD

**Issue by thephoenixlodge** [lorddusk/Bagginses#6]
While a bag is on the hotbar and open, the number hotkeys can be used to swap the position of the bag in hand with another bag in the inventory. 
Eg, bag in hotbar slot 1, opened. second bag in inventory. Player presses '1' on their keyboard while hovering over the second bag and the two swap positions.
When doing so, the contents of the first bag will be replicated in the second, though only if the contents had been present when the bag was opened. Items placed in since the bag was opened but before the bags were swapped will be placed in the second bag rather than the first.
It's a minor issue in a very niche situation, but unfortunately it was brought to my attention by a user of my modpack posting it publicly in the FTB forums thread.

**Comment by lorddusk** [comment]
So...let me get this right.

You have a bag in slot 1 and another bag in slot 2. You open bag 1 and
switch with the hotkeys bag 2 to slot 1. Which will make the contents of
bag 1 duplicate in bag 2?

**Comment by thephoenixlodge** [comment]
Correct

**Comment by lorddusk** [comment]
Fixed in 1.2.1

**Comment by SirWilli** [comment]
The dupe still works in version 2.0.1

**Comment by lorddusk** [comment]
Fixed in 2.1.x
