### ISSUE TITLE
Only Void and Ender bags...

### ISSUE THREAD

**Issue by Grabby83** [lorddusk/Bagginses#60]
So I just started modding my minecraft and these are the only two bags i can see, i can also so the bag upgrade but not the bags themselves... Bagginses-1.10-3.0.1a

**Comment by lorddusk** [comment]
I quote from the curseforge main page :

> Where are all my bags? Check your config
> only see 3 bags? Check your config
> Check the config on how to whitelist/toggle bags.

**Comment by AKTheKnight** [comment]
Bottom of this page: https://github.com/lorddusk/Bagginses/wiki/Bagginses-Config

**Comment by Grabby83** [comment]
It won't let me change the config

**Comment by AKTheKnight** [comment]
Go to your minecraft folder. Go to config/bagginses. Bagginses.cfg. Change whitelist = true to false

**Comment by Grabby83** [comment]
Got it, thanks... maybe I should read more often lol

**Comment by AKTheKnight** [comment]
It's fine. Hope you enjoy the mod :)
