### ISSUE TITLE
[1.10.2] bug with metadata in pickup mode

### ISSUE THREAD

**Issue by Tsukiumy** [lorddusk/Bagginses#62]
bagginses 3.0.3
tinkers construct 2.4.0-jenkins 312
forge 12.18.1.2046

not a game breaking bug, with the bag in pickup mode, when you break the first casting basin or a casting table, it will go to the bag, but the subsequent ones will be converted to the first one breaked indiferently to what one it was
a few pics to try to explain better
http://imgur.com/a/YYome
edit: forget to activate F3+H, but it has the same item ID, but one is /0 and the other is /1(forgot what the name of that tag )

edit time: so, it seems that it can mess anithing that uses metadata, storage drawers for example(sealed for transport and forgot to deactivate the mode) so it can become a realy game breaking if used in some combinations, like putting a nether star in a drawer, seal it with a paking tape break first, seal a bunch of drawers, break, repeat. it can break ic2 and substratum oregen, as these mods utilize metadata for its ores.

**Comment by AKTheKnight** [comment]
Ahh I see. Thanks for reporting this, I'm away on holiday but I think I know the problem and I'll get a fix out as soon as I'm home

**Comment by AKTheKnight** [comment]
Fixed in https://github.com/lorddusk/Bagginses/commit/c82b6eb79a71a8fe25fb374446e92a2004648175
