### ISSUE TITLE
No chat output when changing modes

### ISSUE THREAD

**Issue by tivec** [lorddusk/Bagginses#63]
I crafted a tier 3 white bag and used shift-right click to change the mode. No chat message showed up, and this error was put in the server log:

http://pastebin.com/GgKLstct

Using version 1.10-3.0.3.

Full server log: 
https://gist.github.com/6ff20842f147764469f386cdfa13465a

latest.log:
https://gist.github.com/fa4b77079f44ac191b41fbf6982c970c

Forge version: 12.18.1.2065.

Steps to reproduce:
1. Hold baggins tier 3 bag in a hotbar slot.
2. Right click.
3. Examine server output for error message.

What I expected:
* Messages saying the mode had changed.

**Comment by AKTheKnight** [comment]
What version of minecraft were you using?

**Comment by tivec** [comment]
I am playing on 1.10.2. The messages showed up on t1 bags, iirc.

**Comment by AKTheKnight** [comment]
Hmm weird. Could I possibly get the full log please

**Comment by tivec** [comment]
There's really nothing more to the message. You'll see it repeating in the log here, that's because I kept trying.

http://pastebin.com/iK2WAHW1

**Comment by lorddusk** [comment]
I'll leave this here... https://github.com/lorddusk/Bagginses/blob/master/CONTRIBUTING.MD

**Comment by tivec** [comment]
Main post updated with the data needed as per CONTRIBUTING.MD.

**Comment by AKTheKnight** [comment]
This should be fixed in 3.0.4a https://minecraft.curseforge.com/projects/bagginses/files/2324031

Let me know if you have any more issues :)

**Comment by tivec** [comment]
I will be updating as soon as practically possible for me and give it a try :) Cheers for the quick fix!
