### ISSUE TITLE
[1.10.2] [Bug] Localization undefined in option's controls menu

### ISSUE THREAD

**Issue by SnowShock35** [lorddusk/Bagginses#64]
Hello,

I believe to have found a minor bug with Bagginses, here are the details of my issue:

### Important Information

* Minecraft 1.10.2
* MinecraftForge 12.18.1.2071 (Latest as of reporting
* Bagginses 3.0.4a (According to ingame mcmod.info file)

### Issue Description

The issue is very minor. A keybinding was recently added to the mod in order to open bags by pressing a button however, localization for the Options/Controls menu was forgotten. (A Pull Request will be submitted to fix this issue.) 

### Issue Media (Screenshot)

![Issue Media No. 1](http://ss.snowshock35.com/2016/08/1471854280-3833c7de.png)

**Comment by AKTheKnight** [comment]
Oops I might have forgotten to add it :P Thanks for the PR
