### ISSUE TITLE
Console spamming NPE

### ISSUE THREAD

**Issue by LemADEC** [lorddusk/Bagginses#71]
### What were you doing when the issue happened? ###
I was watching console for errors.
We had 2 players online on a frash map, noone has a bag.
Maybe a mob had a bag?

### What did you expect to happen? ###
No spam in console

### What happened instead? ###
```
[20:58:41] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
>       at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
>       at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
>       at nl.lang2619.bagginses.helpers.Messages.OpenBagMessage$MyMessageHandler.handle(OpenBagMessage.java:49) ~[OpenBagMessage$MyMessageHandler.class:?]
>       at nl.lang2619.bagginses.helpers.Messages.OpenBagMessage$MyMessageHandler.lambda$onMessage$0(OpenBagMessage.java:42) ~[OpenBagMessage$MyMessageHandler.class
:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
>       ... 5 more
```

### Crashlog on pastebin/gist ###
not applicable

### Forge and Minecraft version? ###
forge-1.10.2-12.18.1.2092-universal.jar
Bagginses-1.10.2-3.0.4b.jar

### Any other known modifications to Minecraft/Forge itself that are known to cause issues? ###
nope

### Any other info which might help. ###
nope

**Comment by AKTheKnight** [comment]
Was one of you pressing C or whichever other key you may have set for the Bagginses bag open?

**Comment by LemADEC** [comment]
It's possible one the girls used C key for push to talk.

Any idea how to fix that?

**Comment by AKTheKnight** [comment]
Yep I'll take a look at it and see what I can do. For now I would suggest changing the keybinding for the bag to something else

**Comment by AKTheKnight** [comment]
Thanks for reporting this. 3.0.4c is about to be released on Curseforge and should fix the issue, let me know if it doesn't seem to have worked :)
