### ISSUE TITLE
Crash trying to swap item position

### ISSUE THREAD

**Issue by Galvanize** [lorddusk/Bagginses#72]
### What were you doing when the issue happened? ###
Trying to swap items positions using number keys while bag was open. But I clicked the bag number position by mistake.

### What did you expect to happen? ###
Swap items position

### What happened instead? ###
Crash

### Crashlog on pastebin/gist ###
http://pastebin.com/QvgpfZwX

### Forge and Minecraft version? ###
forge-12.18.1.2088

**Comment by AKTheKnight** [comment]
Thanks for reporting this. 3.0.4c is about to be released on Curseforge and should fix the issue, let me know if it doesn't seem to have worked :)
