### ISSUE TITLE
[3.0.4b] Issue with NBT in pickup mode

### ISSUE THREAD

**Issue by Belgabor** [lorddusk/Bagginses#74]
Similar to #62, but affects items with differing NBT. They get stacked even if they should not. For example it "unifies" Ender IO broken spawners and Forestry drones, effectively potentially destroying rare items.

**Comment by AKTheKnight** [comment]
Thanks for reporting this. 3.0.4c is about to be released on Curseforge and should fix the issue, let me know if it doesn't seem to have worked :)
