### ISSUE TITLE
Getting achievements multiple times

### ISSUE THREAD

**Issue by xenoflot** [lorddusk/Bagginses#76]
Howdy, just a very minor bug. Each time I craft a Bagginses bag, I get the achievements again.

Bagginses 3.0.4e

**Comment by AKTheKnight** [comment]
Hmm. That's a weird one. I'll see what I can do :)

**Comment by AKTheKnight** [comment]
3.0.4f has been released and should fix the issue. Let me know if you have any issues :)

**Comment by xenoflot** [comment]
I'll update the server Soon(TM)! Thanks!
