### ISSUE TITLE
CTD Rendering tooltip

### ISSUE THREAD

**Issue by xenoflot** [lorddusk/Bagginses#77]
### What were you doing when the issue happened? ###
Hitting '1' a few times, toggling a stack of dirt between inventory and hotbar slot 1

### What did you expect to happen? ###
BoP Silty Dirt and Soulbound Black Tier 3 bag to exchange places

### What happened instead? ###
Kaboom! :(

### Crashlog on pastebin/gist ###
http://pastebin.com/EDXQNv8a

### Forge and Minecraft version? ###
Minecraft 1.10.2
Forge 2122
Bagginses 3.0.4e

**Comment by xenoflot** [comment]
Thanks!

**Comment by AKTheKnight** [comment]
3.0.4g (Wow, we're getting a way down the alphabet) is up on CurseForge pending approval and should fix the issue :)

**Comment by xenoflot** [comment]
Almost ready for 3.0.5! :-)
