### ISSUE TITLE
Crash when closing bag after adding non-vanilla items to bag.

### ISSUE THREAD

**Issue by Zarepheth** [lorddusk/Bagginses#78]
### What were you doing when the issue happened? ###
I was closing the bag inventory by pressing the [E] key.

### What did you expect to happen? ###
I expected the inventory to close and the game to continue.

### What happened instead? ###
The game froze. After a while, the game shutdown and the game launcher displayed a crash report.

### Crashlog on pastebin/gist ###
[https://gist.github.com/Zarepheth/fc6171eadec7a865dfdc4ba7d5c0ee18](https://gist.github.com/Zarepheth/fc6171eadec7a865dfdc4ba7d5c0ee18)

### Forge and Minecraft version? ###
Forge: "forge-1.10.2-12.18.2.2125"
Minecraft: 1.10.2

### Any other known modifications to Minecraft/Forge itself that are known to cause issues? ###
There are many installed mods, but whether or not they cause issue related to this crash is unknown. The game was playable and working fine (though a bit laggy) prior to modifying the Bagginses config file.

### Any other info which might help. ###
Just before the crash, I had shut down Minecraft (with the launcher still open) and modified the Bagginses config file. It originally was white-listing all items covered by a single asterisk "*"
 for each bag. Because I wanted items from all installed mods to be allowed in my Bagginses bag, I changed it to white-list all items in all mods "*:*". 

After restarting Minecraft and reloading the world, the first thing I did was open the Bagginses bag inventory and check to see if all the items I wanted stored in the bag (most from other mods, such as Biomes O'Plenty). When I attempted to close the bag, the game crashed.

The Bagginses Configuration file and the Crash Log are in the linked Gist.

**Comment by AKTheKnight** [comment]
Hmm, I've tried to reproduce this and been unable to at all. The crash appears to be due to an issue with an array, but the log shows no calls from Bagginses that could cause it. Does the crash happen still? Do you happen to have the world file you could send me?

**Comment by Zarepheth** [comment]
No, the problem has not recurred.

After writing the initial post and going back to the game, everything worked. Since the Bagginses config file change was the only change (and occurred immediately before restarting the game and the subsequent crash), and since I was adding some non-vanilla items to a Bagginses bag when the crash occurred I assumed it was related to Bagginses.

Since the problem has not returned, I'll close this issue.

**Comment by AKTheKnight** [comment]
Ahh I see. It's an obvious assumption so don't worry about it.

If the issue does come up again feel free to reopen this issue and I'll take another look at what I can do
