### ISSUE TITLE
[Feature Request]- Whitelisted Item shift tooltips for bags

### ISSUE THREAD

**Issue by SnowShock35** [lorddusk/Bagginses#8]
Add a shift tooltip that allows the player to see what mod/items/blocks/things are able to go into the bag this way the player doesn't have to reference the config file or try every item that is added

**Comment by AKTheKnight** [comment]
This has been open for a while and I think it could be a good addition to the mod. Would you want this to include colour code usage? Or just plain text?

**Comment by SnowShock35** [comment]
I mean whatever you feel works tbh. Colour codes could be cool 

I mean perhaps you could have it so when the bag UI is open and you hover  over items it'll say if it can be stored in that bag. saves having a huge list or something

**Comment by AKTheKnight** [comment]
I'll see what I can do
